# Generated by Django 2.2.3 on 2019-07-10 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0005_remove_post_tv_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tv_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='site_tv.Choice'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
